Data source : https://www.kaggle.com/datasets/ashyou09/apple-global-product-sales-dataset

In [1]:
## all the necessary libaries imported 

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [8]:
## importing csv file
df = pd.read_csv('data/apple_global_sales_dataset.csv')
## looking at top 5 records
df.head(5)
df.shape ### we have 27 featuers and 11500 records

(11500, 27)

### 3. Data Checks to perform

- Check Missing values
- Check Duplicates
- Check data type
- Check the number of unique values of each column
- Check statistics of data set
- Check various categories present in the different categorical column

In [30]:
## Check Misssing Values
##these are the features with nan value
feature_with_na = [feature for feature in df.columns if df[feature].isnull().sum()]
for feature in feature_with_na:
    print(feature,np.round(df[feature].isnull().mean()*100,5),'% missing value')

storage 41.77391 % missing value
previous_device_os 70.05217 % missing value
customer_rating 29.21739 % missing value

In [40]:
## storage of products like watch and airposd missing so writing unapplicable in those
df['storage'] = df['storage'].fillna('Not Applicable')
##imputing the na values with "unknown"
df['previous_device_os'] = df['previous_device_os'].fillna('Unknown')
## since there are lot of values missing in customer rating we are dropping this feature
df.drop(columns=['customer_rating'],inplace=True)

In [45]:
## we have no duplicate values
df.duplicated().sum()

0

In [47]:
df.nunique()

sale_id                   11500
sale_date                  1096
year                          3
quarter                       4
month                        12
country                      47
region                        8
city                        514
product_name                 43
category                      6
storage                      11
color                        20
unit_price_usd            10616
discount_pct                  7
units_sold                    8
discounted_price_usd      10787
revenue_usd               11142
currency                     38
fx_rate_to_usd               38
revenue_local_currency    11445
sales_channel                 6
payment_method                7
customer_segment              4
customer_age_group            5
previous_device_os            7
return_status                 3
dtype: int64

In [48]:
df.describe()

,year,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,fx_rate_to_usd,revenue_local_currency
count,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,1.150000e+04
mean,2022.997304,807.851191,3.841565,2.023478,777.365478,1568.319065,1029.406647,1.464369e+06
std,0.821747,1112.437595,4.783161,1.443599,1072.915122,2839.759822,4072.334957,9.941160e+06
min,2022.000000,26.690000,0.000000,1.000000,22.730000,23.000000,0.790000,2.130000e+01
25%,2022.000000,180.147500,0.000000,1.000000,178.297500,305.740000,0.920000,1.041693e+03
50%,2023.000000,593.905000,2.000000,1.000000,573.420000,833.040000,7.240000,6.164160e+03
75%,2024.000000,958.387500,7.000000,3.000000,928.567500,1748.360000,91.500000,7.471653e+04
max,2024.000000,7551.010000,15.000000,8.000000,7551.010000,59529.520000,24500.000000,5.075175e+08

In [52]:
numeric_features = [feature for feature in df.columns if df[feature].dtype != 'O']
categorical_features = [feature for feature in df.columns if df[feature].dtype == 'O']

print('We have {} numerical features : {}'.format(len(numeric_features), numeric_features))
print('\nWe have {} categorical features : {}'.format(len(categorical_features), categorical_features))


## we had a total of 27 featuers, we dropped customer_rating feature because of 29% missing values now we have 8 numerical feature and 18 categorical features

We have 8 numerical features : ['year', 'unit_price_usd', 'discount_pct', 'units_sold', 'discounted_price_usd', 'revenue_usd', 'fx_rate_to_usd', 'revenue_local_currency']

We have 18 categorical features : ['sale_id', 'sale_date', 'quarter', 'month', 'country', 'region', 'city', 'product_name', 'category', 'storage', 'color', 'currency', 'sales_channel', 'payment_method', 'customer_segment', 'customer_age_group', 'previous_device_os', 'return_status']

In [97]:
df.columns
df[categorical_features]
# sale_id needs to be dropped as well
# need segregate sale_date to day month and year and then drop sale_date because quater and month are already being covered
# also currency can be droppen since we have a feature of country
# city can also be dropped since we are having featuers like country, region 
# fx_rate_to_usd and revenue_local_currency these are just currency conversion artifacts.
# discounted_price_usd carries zero new information that unit_price_usd and discount_pct together don't already tell the model.

,sale_id,sale_date,quarter,month,country,region,city,product_name,category,storage,color,currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,return_status
0,APPL-00000001,2022-01-03,Q1,January,Argentina,South America,Buenos Aires,AirPods (3rd Gen),AirPods,Not Applicable,Starlight,ARS,Third-Party Retailer,Cash,Government,45–54,Unknown,Kept
1,APPL-00000002,2022-01-04,Q1,January,Argentina,South America,Buenos Aires,USB-C Woven Charge Cable,Accessories,Not Applicable,Black,ARS,Authorized Reseller,Debit Card,Business,45–54,Unknown,Kept
2,APPL-00000003,2022-05-18,Q2,May,Argentina,South America,Buenos Aires,Apple Watch Series 8,Apple Watch,Not Applicable,Titanium,ARS,Corporate / B2B,Credit Card,Individual,18–24,Unknown,Kept
3,APPL-00000004,2022-05-23,Q2,May,Argentina,South America,Buenos Aires,MacBook Pro 14-inch (M3),Mac,1 TB SSD,Starlight,ARS,Carrier Store,Credit Card,Education,45–54,Unknown,Kept
4,APPL-00000005,2022-07-13,Q3,July,Argentina,South America,Buenos Aires,Apple Watch Ultra 2,Apple Watch,Not Applicable,Midnight,ARS,Apple Store,Net Banking,Education,18–24,Unknown,Kept
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11495,APPL-00011496,2024-02-08,Q1,February,Vietnam,Asia,Nha Trang,Apple Watch Series 9,Apple Watch,Not Applicable,Natural,VND,Third-Party Retailer,Gift Card,Individual,18–24,Unknown,Kept
11496,APPL-00011497,2024-02-15,Q1,February,Vietnam,Asia,Nha Trang,Mac Pro (M2 Ultra),Mac,256 GB SSD,Midnight,VND,Corporate / B2B,Gift Card,Education,45–54,Unknown,Kept
11497,APPL-00011498,2024-08-28,Q3,August,Vietnam,Asia,Nha Trang,iPhone 15,iPhone,128 GB,Deep Purple,VND,Authorized Reseller,Debit Card,Government,35–44,iOS 16,Kept
11498,APPL-00011499,2024-08-31,Q3,August,Vietnam,Asia,Nha Trang,iPhone SE (3rd Gen),iPhone,512 GB,Black,VND,Apple Store,EMI / Installment,Education,55+,iOS 17,Kept
11499,APPL-00011500,2024-10-10,Q4,October,Vietnam,Asia,Nha Trang,iPhone 15 Pro Max,iPhone,512 GB,Silver,VND,Online (Apple.com),EMI / Installment,Individual,35–44,Other,Kept

In [ ]:
df['sale_date'] = pd.to_datetime(df['sale_date']0)
df['day'] = df['sale_date'].dt.day
df['day_of_week'] = df['sale_date'].dt.day_of_week

In [99]:
df.drop(columns=[
    'sale_id',           
    'sale_date',         
    'discounted_price_usd',      
    'revenue_local_currency',   
    'fx_rate_to_usd',           
    'currency'           
], inplace=True)

In [107]:
df.drop(columns=['city'], inplace= True)

In [123]:
# df.columns.shape
df['country'].unique().shape
df['region'].unique().shape

## here we can also drop country since country has 47 unique values, where it is being covered in the 'region' feature as it groups countries or for this we can do target encoding(encode by mean return rate per country) through which it will be much clean because if we use OHE it add 47 new columns 

df['product_name'].unique().shape
## same as above reason dropping product_name column it will be covered in category
df['color'].unique().shape
## also color is a feature which has 20 more unique values which does not impact return status alot which is over target variable

(20,)

In [ ]:
df.drop(columns=['product_name','color'], inplace= True) ## we will be doing target enconding for country feature
df.columns

Index(['year', 'quarter', 'month', 'country', 'region', 'category', 'storage',
       'unit_price_usd', 'discount_pct', 'units_sold', 'revenue_usd',
       'sales_channel', 'payment_method', 'customer_segment',
       'customer_age_group', 'previous_device_os', 'return_status', 'day',
       'day_of_week'],
      dtype='object')